# @name userCreate
@token = {{userCreate.response.body.$.token}}
curl -X POST http://localhost:8000/api/users/create \ 
-d "name=kinder&email=ferraz.alkindar@gmail.com&password=123456&password_confirmation=123456" \
-H "Accept: application/json"


###
# @name login
@token = {{login.response.body.$.token}}
curl -X POST http://localhost:8000/api/users/login \ 
-d "email=ferraz.alkindar@gmail.com&password=123456" \ 
-H "Accept: application/json"

###

# @name logout
curl -X POST http://localhost:8000/api/users/logout \
-H "Authorization: Bearer {{token}}" \
-H "Accept: application/json"

###

# @name userRecipes
curl http://localhost:8000/api/recipes \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}"

###

# @name recipeCreate
curl -X POST http://localhost:8000/api/recipes \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d  "name=bolo de banana&url=http://paolacarossella.com"

###

# @name findRecipe
curl -X GET http://localhost:8000/api/recipes/2 \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \

###

# @name updateRecipe
curl -X PUT http://localhost:8000/api/recipes/1 \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d "name=Lasanha acebolada"

###

# @name deleteRecipe
curl -X DELETE http://localhost:8000/api/recipes/1 \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}"

###

# @name getUserCalendar 
curl -X GET http://localhost:8000/api/calendar \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}"

###

# @name getUserCalendarWeek 
curl -X POST http://localhost:8000/api/week \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d "date_reference=2022-11-14"

###
# @name saveRecipeForDay

curl -X POST http://localhost:8000/api/calendar \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d "id_recipe=1&date=2022-11-24T10:46:16.000Z"

###
# @name saveRecipeForDay2

curl -X POST http://localhost:8000/api/calendar \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d "id_recipe=2&date=2022-11-13T10:46:16.000Z"


###
# @name updateRecipeForDay

curl -X PUT http://localhost:8000/api/calendar/1 \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}" \
-d "id_recipe=2"

###
# @name deleteRecipeForDay

curl -X DELETE http://localhost:8000/api/calendar/1 \
-H "Accept: application/json" \
-H "Authorization: Bearer {{token}}"
