openapi: 3.0.3
info:
  title: receitineas
  description: ''
  version: 1.0.0
servers:
  -
    url: '127.0.0.1:8000'
paths:
  /api/users/create:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: tempora
                email:
                  type: string
                  description: ''
                  example: medhurst.mabelle@example.com
                password:
                  type: string
                  description: ''
                  example: '_0/qjhs^x5i]u1U8J-'
              required:
                - name
                - email
                - password
      security: []
  /api/users/login:
    post:
      summary: ''
      operationId: postApiUsersLogin
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: grayce.pfannerstill@example.net
                password:
                  type: string
                  description: ''
                  example: ']$Ua|&,lm]KXTd/vU7u}'
              required:
                - email
                - password
      security: []
  /api/recipes:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eos
                url:
                  type: string
                  description: ''
                  example: 'http://www.koss.org/'
              required:
                - name
                - url
      security: []
  '/api/recipes/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the recipe.'
        example: 4
        required: true
        schema:
          type: integer
  /api/calendar:
    post:
      summary: 'Associar uma receita a um dia especifico.'
      operationId: associarUmaReceitaAUmDiaEspecifico
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_recipe:
                  type: integer
                  description: ''
                  example: 20
                date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2022-11-29T14:15:32'
              required:
                - id_recipe
                - date
      security: []
  '/api/calendar/{id}':
    put:
      summary: 'Atualiza a receita de um dia especifico.'
      operationId: atualizaAReceitaDeUmDiaEspecifico
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Deleta uma associacao de receita e dia.'
      operationId: deletaUmaAssociacaoDeReceitaEDia
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the calendar.'
        example: blanditiis
        required: true
        schema:
          type: string
  /api/users/logout:
    post:
      summary: ''
      operationId: postApiUsersLogout
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/week:
    post:
      summary: ''
      operationId: postApiWeek
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_reference:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2022-11-29T14:15:32'
              required:
                - date_reference
      security: []
tags:
  -
    name: Endpoints
    description: ''
